version: "3.3"

services:

  lcp:
    build: .
    ports:
      - ${LCP_PORT:-8080}:6081
    environment:
      - LCP_BIN=${LCP_BIN:-lcp.d64}
      - LCP_VICE_OPTS=${LCP_VICE_OPTS:--VICIIfilter 0}
    volumes:
      - ./${LCP_BIN:-lcp.d64}:/${LCP_BIN:-lcp.d64}
